title: Seolha Lee # your name (or website title) here
logo: "/images/IMG_5864.PNG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Urban Governance
  <br>
  Data Science
  <br>
  Critical theories
  <br>
  Interactions between
  <br>
  Human - Place - Technology
  <br><br> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
extra_javascript:
    - js/main.js 
